import AdminLayout from "../../components/layout/AdminLayout";

export default function Reports({ user }: { user?: any }) {
  return (
    <AdminLayout title="System Reports" user={user}>
      <div className="p-4">
        <h1 className="text-2xl font-bold mb-4">System Reports</h1>

        {/* Reports Overview */}
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6">
          <div className="p-4 bg-white rounded-2xl shadow">
            <h3 className="text-sm text-gray-500">Total Reports</h3>
            <p className="text-2xl font-bold">120</p>
          </div>
          <div className="p-4 bg-white rounded-2xl shadow">
            <h3 className="text-sm text-gray-500">Pending Reports</h3>
            <p className="text-2xl font-bold text-yellow-600">15</p>
          </div>
          <div className="p-4 bg-white rounded-2xl shadow">
            <h3 className="text-sm text-gray-500">Approved Reports</h3>
            <p className="text-2xl font-bold text-green-600">95</p>
          </div>
          <div className="p-4 bg-white rounded-2xl shadow">
            <h3 className="text-sm text-gray-500">Rejected Reports</h3>
            <p className="text-2xl font-bold text-red-600">10</p>
          </div>
        </div>

        {/* Reports Table */}
        <div className="bg-white rounded-2xl shadow p-4">
          <h2 className="text-lg font-semibold mb-4">Recent Reports</h2>
          <table className="w-full text-sm text-left">
            <thead>
              <tr className="border-b">
                <th className="py-2 px-4">Report Name</th>
                <th className="py-2 px-4">Generated By</th>
                <th className="py-2 px-4">Status</th>
                <th className="py-2 px-4">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b">
                <td className="py-2 px-4">Monthly Clearance Summary</td>
                <td className="py-2 px-4">Admin</td>
                <td className="py-2 px-4 text-green-600">Approved</td>
                <td className="py-2 px-4">
                  <button className="text-blue-500">View</button> |{" "}
                  <button className="text-red-500">Delete</button>
                </td>
              </tr>
              <tr className="border-b">
                <td className="py-2 px-4">Pending Clearances</td>
                <td className="py-2 px-4">Staff</td>
                <td className="py-2 px-4 text-yellow-600">Pending</td>
                <td className="py-2 px-4">
                  <button className="text-blue-500">View</button> |{" "}
                  <button className="text-green-500">Approve</button> |{" "}
                  <button className="text-red-500">Reject</button>
                </td>
              </tr>
              <tr>
                <td className="py-2 px-4">Rejected Clearances</td>
                <td className="py-2 px-4">Admin</td>
                <td className="py-2 px-4 text-red-600">Rejected</td>
                <td className="py-2 px-4">
                  <button className="text-blue-500">View</button> |{" "}
                  <button className="text-red-500">Delete</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Quick Actions */}
        <div className="mt-6">
          <h2 className="text-lg font-semibold mb-4">Quick Actions</h2>
          <div className="space-y-2">
            <button className="w-full bg-blue-500 text-white py-2 rounded">Generate New Report</button>
            <button className="w-full bg-green-500 text-white py-2 rounded">Approve All Pending Reports</button>
            <button className="w-full bg-red-500 text-white py-2 rounded">Delete All Rejected Reports</button>
          </div>
        </div>
      </div>
    </AdminLayout>
  );
}